#pragma once
#include "Base/hplatform.h"
#include "Base/hcore.h"
#include "Base/hlog.h"
namespace RHI
{

	static const uint8_t								k_max_image_outputs = 8;                // Maximum number of images/render_targets/fbo attachments usable.
	static const uint8_t								k_max_descriptor_set_layouts = 8;       // Maximum number of layouts in the pipeline.
	static const uint8_t								k_max_shader_stages = 5;                // Maximum simultaneous shader stages. Applicable to all different type of pipelines.
	static const uint8_t								k_max_descriptors_per_set = 32;         // Maximum list elements for both descriptor set layout and descriptor sets.
	static const uint8_t								k_max_vertex_streams = 16;
	static const uint8_t								k_max_vertex_attributes = 16;


#define RHI_ENUM_CLASS_OPERATORS(e_) \
    static_assert(std::is_enum<e_>::value, "Must be enum type"); \
    using _T = std::underlying_type_t<e_>; \
    inline e_ operator&(e_ a, e_ b) { return static_cast<e_>(static_cast<_T>(a) & static_cast<_T>(b)); } \
    inline e_ operator|(e_ a, e_ b) { return static_cast<e_>(static_cast<_T>(a) | static_cast<_T>(b)); } \
    inline e_& operator|=(e_& a, e_ b) { a = a | b; return a; } \
    inline e_& operator&=(e_& a, e_ b) { a = a & b; return a; } \
    inline e_ operator~(e_ a) { return static_cast<e_>(~static_cast<_T>(a)); } \
    inline bool is_set(e_ val, e_ flag) { return (val & flag) != static_cast<e_>(0); } \
    inline void flip_bit(e_& val, e_ flag) { val = is_set(val, flag) ? (val & (~flag)) : (val | flag); }

	struct Rect2D {
		float                             x = 0.0f;
		float                             y = 0.0f;
		float                             width = 0.0f;
		float                             height = 0.0f;
	}; // struct Rect2D

	//
	//
	struct Rect2DInt {
		int16_t                         x = 0;
		int16_t                         y = 0;
		uint16_t						width = 0;
		uint16_t						height = 0;
	}; // struct Rect2D
	struct Viewport {
		Rect2DInt							rect;
		float								min_depth = 0.0f;
		float								max_depth = 0.0f;
	}; // struct Viewport
	
	//for non immediately delete, just call smart pointer . reset() directly
#define RHI_RELEASE_IMMEDIATELY(res)\
{\
	(res)->immediate_deletion = true;\
	(res).reset();\
}

	enum ASH_API AshImageType {
		Ash_Texture1D, Ash_Texture2D, Ash_Texture3D, Ash_TextureCube, Ash_Texture_1D_Array, Ash_Texture_2D_Array, Ash_Texture_Cube_Array, Count
	};

	typedef struct AshDepthStencilValue {
		float       depth;
		uint32_t    stencil;
	} AshDepthStencilValue;

	typedef union AshColorValue
	{
		enum valueType
		{
			T_float32,
			T_int32,
			T_uint32
		};
		valueType v_type = T_float32;
		float float32[4];
		int32_t int32[4];
		uint32_t uint32[4];
		AshColorValue()
		{
			for (int i = 0; i < 4; ++i) {
				float32[i] = 0.0f; 
			}
			v_type = T_float32;
		};
		explicit AshColorValue(float value) {
			for (int i = 0; i < 4; ++i) {
				float32[i] = value;
			}
			v_type = T_float32;
		}
		explicit AshColorValue(int32_t value) {
			for (int i = 0; i < 4; ++i) {
				int32[i] = value;
			}
			v_type = T_int32;
		}
		explicit AshColorValue(uint32_t value) {
			for (int i = 0; i < 4; ++i) {
				uint32[i] = value;
			}
			v_type = T_uint32;
		}
		AshColorValue(float r, float g, float b, float a) {
			float32[0] = r; float32[1] = g; float32[2] = b; float32[3] = a;
			v_type = T_float32;
		}

		AshColorValue(int32_t r, int32_t g, int32_t b, int32_t a) {
			int32[0] = r; int32[1] = g; int32[2] = b; int32[3] = a;
			v_type = T_int32;
		}

		AshColorValue(uint32_t r, uint32_t g, uint32_t b, uint32_t a) {
			uint32[0] = r; uint32[1] = g; uint32[2] = b; uint32[3] = a;
			v_type = T_uint32;
		}
	};

	

	namespace AshQueueType {
		enum Enum {
			Graphics, Compute, CopyTransfer, Ignored, Count
		};

		enum Mask {
			Graphics_mask = 1 << 0, Compute_mask = 1 << 1, CopyTransfer_mask = 1 << 2, Ignored_mask = 1 << 3,Count_mask = 1 << 4
		};

		static const char* s_value_names[] = {
			"Graphics", "Compute", "CopyTransfer","Ignored", "Count"
		};

		static const char* to_string(Enum e) {
			return ((uint32_t)e < Enum::Count ? s_value_names[(int)e] : "unsupported");
		}
	} // namespace QueueType

	typedef enum AshResourceViewDimension : uint8_t
	{
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURE1D = 0,
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURE2D = 1,
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURE3D = 2,
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURECUBE = 3,
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURE1D_ARRAY = 4,
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURE2D_ARRAY = 5,
		ASH_RESOURCE_VIEW_DIMENSION_TEXTURECUBE_ARRAY = 6,
		ASH_RESOURCE_VIEW_DIMENSION_BUFFER = 7,
		ASH_IMAGE_VIEW_TYPE_MAX_ENUM = 0x7FFFFFFF
	} AshResourceViewDimension;



	typedef enum AshFormat {
		ASH_FORMAT_UNDEFINED = 0,
		ASH_FORMAT_R8G8B8A8_UNORM,
		ASH_FORMAT_R8G8B8A8_SNORM,
		ASH_FORMAT_R8G8B8A8_SRGB,
		ASH_FORMAT_R8G8B8A8_UINT,

		ASH_FORMAT_R8_UNORM,
		ASH_FORMAT_R8G8_UNORM,
		ASH_FORMAT_R16G16_UINT,
		ASH_FORMAT_B8G8R8_UNORM,
		ASH_FORMAT_R8G8B8_UNORM,

		ASH_FORMAT_B8G8R8A8_UNORM,
		ASH_FORMAT_B8G8R8A8_SRGB,
		ASH_FORMAT_R16G16B16A16_UNORM,

		ASH_FORMAT_R16G16B16A16_SFLOAT,
		ASH_FORMAT_R32G32B32A32_SFLOAT,
		ASH_FORMAT_R16_SFLOAT,
		ASH_FORMAT_R16_UINT,

		ASH_FORMAT_R16G16_SFLOAT,
		ASH_FORMAT_R32_SINT,
		ASH_FORMAT_R32_UINT,

		ASH_FORMAT_R32_FLOAT,
		ASH_FORMAT_D24_UNORM_S8_UINT,
		ASH_FORMAT_D16_UNORM,
		ASH_FORMAT_D32_SFLOAT,
		ASH_FORMAT_D32_SFLOAT_S8_UINT,

		ASH_FORMAT_R64_UINT,

		ASH_FORMAT_BC1_RGB_UNORM,
		ASH_FORMAT_BC1_RGBA_UNORM,
		ASH_FORMAT_BC2_UNORM,
		ASH_FORMAT_BC3_UNORM,

		ASH_FORMAT_BC4_UNORM,
		ASH_FORMAT_BC4_SNORM,
		ASH_FORMAT_BC5_UNORM,
		ASH_FORMAT_BC5_SNORM,
		ASH_FORMAT_BC6H_UFLOAT,
		ASH_FORMAT_BC6H_SFLOAT,
		ASH_FORMAT_BC7_UNORM,
		ASH_FORMAT_BC7_SRGB_UNORM,

		ASH_FORMAT_B5G6R5_UNORM_PACK16,
		ASH_FORMAT_A2R10G10B10_UNORM_PACK32,

		ASH_FORMAT_B10G11R11_UFLOAT_PACK32,
		ASH_FORMAT_ETC2_R8G8B8_UNORM_BLOCK,
		ASH_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK,
		ASH_FORMAT_ETC2_R_UNORM_BLOCK,
		ASH_FORMAT_ETC2_R_SNORM_BLOCK,
		ASH_FORMAT_ETC2_RG_UNORM_BLOCK,
		ASH_FORMAT_ETC2_RG_SNORM_BLOCK,

		ASH_FORMAT_ASTC_4X4_UNORM_BLOCK,
		ASH_FORMAT_ASTC_6X6_UNORM_BLOCK,
		ASH_FORMAT_ASTC_8X8_UNORM_BLOCK,
		ASH_FORMAT_R32G32_UINT,
		ASH_FORMAT_R32G32B32A32_UINT,

		ASH_FORMAT_R16G16_UNORM,

		ASH_FORMAT_R8_UINT,

		ASH_FORMAT_R16_UNORM,
		ASH_FORMAT_COUNT
	} AshFormat;


	typedef enum AshColorSpace {
		ASH_COLOR_SPACE_UNDEFINED = 0,
		ASH_COLOR_SPACE_SRGB_NONLINEAR_KHR,
		ASH_COLOR_SPACE_COUNT
	} AshColorSpace;

	typedef enum AshPresentMode {
		ASH_PRESENT_MODE_UNDEFINED = 0,
		ASH_PRESENT_MODE_MAILBOX_KHR,
		ASH_PRESENT_MODE_IMMEDIATE_KHR,
		ASH_PRESENT_MODE_FIFO_KHR,
		ASH_PRESENT_MODE_FIFO_RELAXED_KHR,
		ASH_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR,
		ASH_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR,
		ASH_PRESENT_MODE_COUNT
	} AshPresentMode;

	typedef enum AshSamplerAddressMode {
		ASH_SAMPLER_ADDRESS_MODE_REPEAT = 0,
		ASH_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT = 1,
		ASH_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE = 2,
		ASH_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER = 3,
		ASH_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE = 4,
		ASH_SAMPLER_ADDRESS_MODE_MAX_ENUM = 0x7FFFFFFF
	} AshSamplerAddressMode;

	typedef enum AshBorderColor {
		ASH_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK = 0,
		ASH_BORDER_COLOR_INT_TRANSPARENT_BLACK = 1,
		ASH_BORDER_COLOR_FLOAT_OPAQUE_BLACK = 2,
		ASH_BORDER_COLOR_INT_OPAQUE_BLACK = 3,
		ASH_BORDER_COLOR_FLOAT_OPAQUE_WHITE = 4,
		ASH_BORDER_COLOR_INT_OPAQUE_WHITE = 5,
		ASH_BORDER_COLOR_FLOAT_CUSTOM_EXT = 1000287003,
		ASH_BORDER_COLOR_INT_CUSTOM_EXT = 1000287004,
		ASH_BORDER_COLOR_MAX_ENUM = 0x7FFFFFFF
	} AshBorderColor;

	typedef enum AshFilter {
		ASH_FILTER_NEAREST = 0,
		ASH_FILTER_LINEAR = 1,
		ASH_FILTER_CUBIC_EXT = 1000015000,//only for min max
		ASH_FILTER_MAX_ENUM = 0x7FFFFFFF
	} AshFilter;

	typedef enum AshCompareOp {
		ASH_COMPARE_OP_NEVER = 0,
		ASH_COMPARE_OP_LESS = 1,
		ASH_COMPARE_OP_EQUAL = 2,
		ASH_COMPARE_OP_LESS_OR_EQUAL = 3,
		ASH_COMPARE_OP_GREATER = 4,
		ASH_COMPARE_OP_NOT_EQUAL = 5,
		ASH_COMPARE_OP_GREATER_OR_EQUAL = 6,
		ASH_COMPARE_OP_ALWAYS = 7,
		ASH_COMPARE_OP_MAX_ENUM = 0x7FFFFFFF
	} AshCompareOp;

	typedef enum AshSamplerReductionMode {
		ASH_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE = 0,
		ASH_SAMPLER_REDUCTION_MODE_MIN = 1,
		ASH_SAMPLER_REDUCTION_MODE_MAX = 2,
		ASH_SAMPLER_REDUCTION_MODE_MAX_ENUM = 0x7FFFFFFF
	} AshSamplerReductionMode;

	typedef enum AshBufferUsageFlagBits : uint32_t
	{
		ASH_BUFFER_USAGE_TRANSFER_SRC_BIT = 0x00000001,
		ASH_BUFFER_USAGE_TRANSFER_DST_BIT = 0x00000002,
		ASH_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000004, // similar to shader resource view via Buffer<format> in hlsl
		ASH_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 0x00000008, // similar to unorder resource view via RWBuffer<format> in hlsl
		ASH_BUFFER_USAGE_UNIFORM_BUFFER_BIT = 0x00000010,
		ASH_BUFFER_USAGE_STORAGE_BUFFER_BIT = 0x00000020,
		ASH_BUFFER_USAGE_INDEX_BUFFER_BIT = 0x00000040,
		ASH_BUFFER_USAGE_VERTEX_BUFFER_BIT = 0x00000080,
		ASH_BUFFER_USAGE_INDIRECT_BUFFER_BIT = 0x00000100,
		ASH_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR = 0x00080000,
		ASH_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR = 0x00100000, // for ray tracing acceleration buffer creation ! enable in vk 1.3
		ASH_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR = 0x00000400, // for ray tracing shader binding table buffer creation! enable in vk 1.3
		ASH_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT = 0x00020000,
		ASH_BUFFER_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	};
	RHI_ENUM_CLASS_OPERATORS(AshBufferUsageFlagBits);
	using AshBufferUsageFlags = uint32_t;
	enum class AshResourceAccessType
	{
		ASH_RESOURCE_ACCESS_GPU_ONLY,
		ASH_RESOURCE_ACCESS_READ,//read back
		ASH_RESOURCE_ACCESS_WRITE,//cpu write gpu read
	};

	typedef enum AshCommandBufferState
	{
		ASH_Idle,
		ASH_Recording,
		ASH_Ended,
		ASH_Submitted,
		ASH_State_Count
	}AshCommandBufferState;

	inline bool has_any_flags(uint32_t Flags, uint32_t Contains)
	{
		return (Flags & Contains) != 0;
	}

	enum AshTextureUsageFlagBits : uint32_t
	{
		ASH_TEXTURE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
		ASH_TEXTURE_USAGE_TRANSFER_DST_BIT = 0x00000002,
		ASH_TEXTURE_USAGE_SAMPLED_BIT = 0x00000004,
		ASH_TEXTURE_USAGE_STORAGE_BIT = 0x00000008,
		ASH_TEXTURE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
		ASH_TEXTURE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
		ASH_TEXTURE_USAGE_TRANSIENT_ATTACHMENT_BIT = 0x00000040,
		ASH_TEXTURE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080,
		ASH_TEXTURE_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	};

	typedef uint32_t AshTextureUsageFlags;

	// Texture creation flags are bitmasks.
	enum AshTextureCreateFlagBits : uint32_t {
		ASH_TEXTURE_CREATE_FLAG_SPARSE = 0x00000001,
		ASH_TEXTURE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	}; 
	typedef uint32_t AshTextureCreateFlags;

	enum AshTextureAspectFlagBits : uint32_t
	{
		ASH_TEXTURE_ASPECT_COLOR_BIT = 0x00000001,
		ASH_TEXTURE_ASPECT_DEPTH_BIT = 0x00000002,
		ASH_TEXTURE_ASPECT_STENCIL_BIT = 0x00000004,
		ASH_TEXTURE_ASPECT_METADATA_BIT = 0x00000008,
		ASH_TEXTURE_ASPECT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	};
	enum AshSampleCountFlag : uint32_t
	{
		ASH_SAMPLE_COUNT_1_BIT = 1,
		ASH_SAMPLE_COUNT_2_BIT = 2,
		ASH_SAMPLE_COUNT_4_BIT = 3,
		ASH_SAMPLE_COUNT_8_BIT = 4,
		ASH_SAMPLE_COUNT_16_BIT = 5,
		ASH_SAMPLE_COUNT_32_BIT = 6,
		ASH_SAMPLE_COUNT_64_BIT = 7
	};

	typedef enum AshSamplerState {
		ASH_SAMPLER_STATE_DEFAULT = 0,
		ASH_SAMPLER_STATE_MAX_ENUM
	} AshSamplerState;

	typedef enum AshLoadOption {
		ASH_LOAD_DONT_CARE,
		ASH_LOAD_LOAD,
		ASH_LOAD_CLEAR,
		ASH_LOAD_MAX_ENUM
	} AshLoadOption;

	typedef enum AshCullModeFlagBits {
		ASH_CULL_MODE_NONE = 0,
		ASH_CULL_MODE_FRONT_BIT = 0x00000001,
		ASH_CULL_MODE_BACK_BIT = 0x00000002,
		ASH_CULL_MODE_FRONT_AND_BACK = 0x00000003,
		ASH_CULL_MODE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	} AshCullModeFlagBits;

	typedef enum AshFrontFace {
		ASH_FRONT_FACE_COUNTER_CLOCKWISE = 0,
		ASH_FRONT_FACE_CLOCKWISE = 1,
		ASH_FRONT_FACE_MAX_ENUM = 0x7FFFFFFF
	} AshFrontFace;

	typedef enum AshFillMode {
		Wireframe, Solid, Point, ModeCount
	} AshFillMode;

	typedef enum AshStencilOp {
		ASH_STENCIL_OP_KEEP = 0,
		ASH_STENCIL_OP_ZERO = 1,
		ASH_STENCIL_OP_REPLACE = 2,
		ASH_STENCIL_OP_INCREMENT_AND_CLAMP = 3,
		ASH_STENCIL_OP_DECREMENT_AND_CLAMP = 4,
		ASH_STENCIL_OP_INVERT = 5,
		ASH_STENCIL_OP_INCREMENT_AND_WRAP = 6,
		ASH_STENCIL_OP_DECREMENT_AND_WRAP = 7,
		ASH_STENCIL_OP_MAX_ENUM = 0x7FFFFFFF
	} AshStencilOp;

	typedef enum AshBlendFactor {
		ASH_BLEND_FACTOR_ZERO = 0,
		ASH_BLEND_FACTOR_ONE = 1,
		ASH_BLEND_FACTOR_SRC_COLOR = 2,
		ASH_BLEND_FACTOR_ONE_MINUS_SRC_COLOR = 3,
		ASH_BLEND_FACTOR_DST_COLOR = 4,
		ASH_BLEND_FACTOR_ONE_MINUS_DST_COLOR = 5,
		ASH_BLEND_FACTOR_SRC_ALPHA = 6,
		ASH_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 7,
		ASH_BLEND_FACTOR_DST_ALPHA = 8,
		ASH_BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 9,
		ASH_BLEND_FACTOR_CONSTANT_COLOR = 10,
		ASH_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = 11,
		ASH_BLEND_FACTOR_CONSTANT_ALPHA = 12,
		ASH_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = 13,
		ASH_BLEND_FACTOR_SRC_ALPHA_SATURATE = 14,
		ASH_BLEND_FACTOR_SRC1_COLOR = 15,
		ASH_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR = 16,
		ASH_BLEND_FACTOR_SRC1_ALPHA = 17,
		ASH_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = 18,
		ASH_BLEND_FACTOR_MAX_ENUM = 0x7FFFFFFF
	} AshBlendFactor;

	typedef enum AshBlendOp {
		ASH_BLEND_OP_ADD = 0,
		ASH_BLEND_OP_SUBTRACT = 1,
		ASH_BLEND_OP_REVERSE_SUBTRACT = 2,
		ASH_BLEND_OP_MIN = 3,
		ASH_BLEND_OP_MAX = 4,
		/*	ASH_BLEND_OP_ZERO_EXT = 1000148000,
			ASH_BLEND_OP_SRC_EXT = 1000148001,
			ASH_BLEND_OP_DST_EXT = 1000148002,
			ASH_BLEND_OP_SRC_OVER_EXT = 1000148003,
			ASH_BLEND_OP_DST_OVER_EXT = 1000148004,
			ASH_BLEND_OP_SRC_IN_EXT = 1000148005,
			ASH_BLEND_OP_DST_IN_EXT = 1000148006,
			ASH_BLEND_OP_SRC_OUT_EXT = 1000148007,
			ASH_BLEND_OP_DST_OUT_EXT = 1000148008,
			ASH_BLEND_OP_SRC_ATOP_EXT = 1000148009,
			ASH_BLEND_OP_DST_ATOP_EXT = 1000148010,
			ASH_BLEND_OP_XOR_EXT = 1000148011,
			ASH_BLEND_OP_MULTIPLY_EXT = 1000148012,
			ASH_BLEND_OP_SCREEN_EXT = 1000148013,
			ASH_BLEND_OP_OVERLAY_EXT = 1000148014,
			ASH_BLEND_OP_DARKEN_EXT = 1000148015,
			ASH_BLEND_OP_LIGHTEN_EXT = 1000148016,
			ASH_BLEND_OP_COLORDODGE_EXT = 1000148017,
			ASH_BLEND_OP_COLORBURN_EXT = 1000148018,
			ASH_BLEND_OP_HARDLIGHT_EXT = 1000148019,
			ASH_BLEND_OP_SOFTLIGHT_EXT = 1000148020,
			ASH_BLEND_OP_DIFFERENCE_EXT = 1000148021,
			ASH_BLEND_OP_EXCLUSION_EXT = 1000148022,
			ASH_BLEND_OP_INVERT_EXT = 1000148023,
			ASH_BLEND_OP_INVERT_RGB_EXT = 1000148024,
			ASH_BLEND_OP_LINEARDODGE_EXT = 1000148025,
			ASH_BLEND_OP_LINEARBURN_EXT = 1000148026,
			ASH_BLEND_OP_VIVIDLIGHT_EXT = 1000148027,
			ASH_BLEND_OP_LINEARLIGHT_EXT = 1000148028,
			ASH_BLEND_OP_PINLIGHT_EXT = 1000148029,
			ASH_BLEND_OP_HARDMIX_EXT = 1000148030,
			ASH_BLEND_OP_HSL_HUE_EXT = 1000148031,
			ASH_BLEND_OP_HSL_SATURATION_EXT = 1000148032,
			ASH_BLEND_OP_HSL_COLOR_EXT = 1000148033,
			ASH_BLEND_OP_HSL_LUMINOSITY_EXT = 1000148034,
			ASH_BLEND_OP_PLUS_EXT = 1000148035,
			ASH_BLEND_OP_PLUS_CLAMPED_EXT = 1000148036,
			ASH_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT = 1000148037,
			ASH_BLEND_OP_PLUS_DARKER_EXT = 1000148038,
			ASH_BLEND_OP_MINUS_EXT = 1000148039,
			ASH_BLEND_OP_MINUS_CLAMPED_EXT = 1000148040,
			ASH_BLEND_OP_CONTRAST_EXT = 1000148041,
			ASH_BLEND_OP_INVERT_OVG_EXT = 1000148042,
			ASH_BLEND_OP_RED_EXT = 1000148043,
			ASH_BLEND_OP_GREEN_EXT = 1000148044,
			ASH_BLEND_OP_BLUE_EXT = 1000148045,*/
		ASH_BLEND_OP_MAX_ENUM = 0x7FFFFFFF
	} AshBlendOp;

	typedef enum AshColorWriteMask {
		Red = 1 << 0, Green = 1 << 1, Blue = 1 << 2, Alpha = 1 << 3, All = Red | Green | Blue | Alpha, ColorCount
	} AshColorWriteMask;

	typedef enum AshVertexInputRate {
		PerVertex, PerInstance, RateCount
	} AshVertexInputRate;

	typedef enum AshIndexType {
		ASH_INDEX_TYPE_UINT16,
		ASH_INDEX_TYPE_UINT32,
		ASH_INDEX_TYPE_MAX_ENUM = 0x7FFFFFFF
	} AshIndexType;

	typedef enum AshVertexComponentFormat {
		Float, Float2, Float3, Float4, Mat4, Byte, Byte4N, UByte, UByte4N, Short2, Short2N, Short4, Short4N, Uint, Uint2, Uint4, FormatCount
	} AshVertexComponentFormat;

	typedef enum AshShaderStageFlagBits {
		ASH_SHADER_STAGE_VERTEX_BIT = 0x00000001,
		ASH_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 0x00000002,
		ASH_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 0x00000004,
		ASH_SHADER_STAGE_GEOMETRY_BIT = 0x00000008,
		ASH_SHADER_STAGE_FRAGMENT_BIT = 0x00000010,
		ASH_SHADER_STAGE_COMPUTE_BIT = 0x00000020,
		ASH_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
		ASH_SHADER_STAGE_ALL = 0x7FFFFFFF,
		ASH_SHADER_STAGE_RAYGEN_BIT_KHR = 0x00000100,
		ASH_SHADER_STAGE_ANY_HIT_BIT_KHR = 0x00000200,
		ASH_SHADER_STAGE_CLOSEST_HIT_BIT_KHR = 0x00000400,
		ASH_SHADER_STAGE_MISS_BIT_KHR = 0x00000800,
		ASH_SHADER_STAGE_INTERSECTION_BIT_KHR = 0x00001000,
		ASH_SHADER_STAGE_CALLABLE_BIT_KHR = 0x00002000,
		ASH_SHADER_STAGE_TASK_BIT_EXT = 0x00000040,
		ASH_SHADER_STAGE_MESH_BIT_EXT = 0x00000080,
		ASH_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = 0x00004000,
		ASH_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI = 0x00080000,
		ASH_SHADER_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	} AshShaderStageFlagBits;

	typedef enum AshPrimitiveTopology {
		ASH_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
		ASH_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
		ASH_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
		ASH_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
		ASH_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
		ASH_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = 5,
		ASH_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = 6,
		ASH_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = 7,
		ASH_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = 8,
		ASH_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9,
		ASH_PRIMITIVE_TOPOLOGY_PATCH_LIST = 10,
		ASH_PRIMITIVE_TOPOLOGY_MAX_ENUM = 0x7FFFFFFF
	} AshPrimitiveTopology;

	typedef enum AshPipelineCreateFlagBits {
		ASH_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT = 0x00000001,
		ASH_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT = 0x00000002,
		ASH_PIPELINE_CREATE_DERIVATIVE_BIT = 0x00000004,
		ASH_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT = 0x00000008,
		ASH_PIPELINE_CREATE_DISPATCH_BASE_BIT = 0x00000010,
		ASH_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT = 0x00000100,
		ASH_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT = 0x00000200,
		ASH_PIPELINE_CREATE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 0x00200000,
		ASH_PIPELINE_CREATE_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT = 0x00400000,
		ASH_PIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR = 0x00004000,
		ASH_PIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR = 0x00008000,
		ASH_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR = 0x00010000,
		ASH_PIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR = 0x00020000,
		ASH_PIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR = 0x00001000,
		ASH_PIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHR = 0x00002000,
		ASH_PIPELINE_CREATE_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHR = 0x00080000,
		ASH_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV = 0x00000020,
		ASH_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR = 0x00000040,
		ASH_PIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR = 0x00000080,
		ASH_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV = 0x00040000,
		ASH_PIPELINE_CREATE_LIBRARY_BIT_KHR = 0x00000800,
		ASH_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT = 0x20000000,
		ASH_PIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT = 0x00800000,
		ASH_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT = 0x00000400,
		ASH_PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV = 0x00100000,
		ASH_PIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT = 0x02000000,
		ASH_PIPELINE_CREATE_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT = 0x04000000,
		ASH_PIPELINE_CREATE_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT = 0x01000000,
		ASH_PIPELINE_CREATE_NO_PROTECTED_ACCESS_BIT_EXT = 0x08000000,
		ASH_PIPELINE_CREATE_PROTECTED_ACCESS_ONLY_BIT_EXT = 0x40000000,
		ASH_PIPELINE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	} AshPipelineCreateFlagBits;

	typedef enum AshDescriptorType {
		ASH_DESCRIPTOR_TYPE_SAMPLER = 0,
		ASH_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = 1,
		ASH_DESCRIPTOR_TYPE_SAMPLED_IMAGE = 2,
		ASH_DESCRIPTOR_TYPE_STORAGE_IMAGE = 3,
		ASH_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER = 4,
		ASH_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER = 5,
		ASH_DESCRIPTOR_TYPE_UNIFORM_BUFFER = 6,
		ASH_DESCRIPTOR_TYPE_STORAGE_BUFFER = 7,
		ASH_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC = 8,
		ASH_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC = 9,
		ASH_DESCRIPTOR_TYPE_INPUT_ATTACHMENT = 10,
		ASH_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK = 1000138000,
		ASH_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE = 1000150000,
		ASH_DESCRIPTOR_TYPE_MAX_ENUM = 0x7FFFFFFF
	} AshDescriptorType;

	typedef struct AshInputAttributeDescription
	{
		uint32_t    location = 0;
		uint32_t    binding = 0;
		AshFormat   format = ASH_FORMAT_UNDEFINED;
		uint32_t    offset = 0;
	}AshInputAttributeDescription;

	typedef struct AshVertexInputBindingDescription {
		uint32_t             binding = 0;
		uint32_t             stride = 0;
		AshVertexInputRate    inputRate = RateCount;
	} AshVertexInputBindingDescription;
	
	typedef enum AshShaderDataType {
		ASH_None,
		ASH_Float32,
		ASH_Vec2,
		ASH_Vec3,
		ASH_Vec4,
		ASH_IVec2,
		ASH_IVec3,
		ASH_IVec4,
		ASH_Mat3,
		ASH_Mat4,
		ASH_Int32,
		ASH_Int,
		ASH_UInt,
		ASH_Bool,
		ASH_Struct,
		ASH_Mat4Array
	} AshShaderDataType;	


}

