#pragma once

#include "vk.h"
#include "KGBaseDef/Public/core_base_macro.h"

#if defined(__ANDROID__)

#include <android/log.h>
// #include "android_native_app_glue.h"
#include <android/configuration.h>
#include <android/native_activity.h>
#include <memory>


// Missing from the NDK
namespace std
{
    template <typename T, typename... Args>
    std::unique_ptr<T> make_unique(Args&&... args)
    {
        return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
    }
} // namespace std

// Global reference to android application object
// extern android_app* androidApp;

extern ANativeActivity* android_native_activity;
#endif


#if defined(__linux__) && !defined(__ANDROID__)
#include <dlfcn.h>
#endif


#define PVR_VULKAN_FUNCTION_POINTER_DECLARATION(function_name) extern PFN_##function_name function_name;


namespace vkfunc
{

#ifdef VK_USE_PLATFORM_WIN32_KHR
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateWin32SurfaceKHR);
#endif

#ifdef VK_USE_PLATFORM_ANDROID_KHR
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateAndroidSurfaceKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetAndroidHardwareBufferPropertiesANDROID);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateSamplerYcbcrConversion);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroySamplerYcbcrConversion);
#endif

#ifdef VK_USE_PLATFORM_OHOS
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateSurfaceOHOS);
#endif

#ifdef VK_USE_PLATFORM_XLIB_KHR
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateXlibSurfaceKHR);
#endif

#ifdef VK_USE_PLATFORM_XCB_KHR
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateXcbSurfaceKHR);
#endif

#ifdef VK_USE_PLATFORM_WAYLAND_KHR
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateWaylandSurfaceKHR);
#endif

#ifdef VK_USE_PLATFORM_MACOS_MVK
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateMacOSSurfaceMVK);
#endif

#ifdef USE_PLATFORM_NULLWS
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceDisplayPropertiesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetDisplayModePropertiesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateDisplayPlaneSurfaceKHR);
#endif
    /******************************* ray tracing ***********************************/
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateAccelerationStructureKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyAccelerationStructureKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBuildAccelerationStructuresKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetAccelerationStructureBuildSizesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetAccelerationStructureDeviceAddressKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdTraceRaysKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdTraceRaysIndirectKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdTraceRaysIndirect2KHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateRayTracingPipelinesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetRayTracingShaderGroupHandlesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdWriteAccelerationStructuresPropertiesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyAccelerationStructureKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBuildAccelerationStructuresIndirectKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkBuildAccelerationStructuresKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCopyAccelerationStructureKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCopyAccelerationStructureToMemoryKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCopyMemoryToAccelerationStructureKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkWriteAccelerationStructuresPropertiesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyAccelerationStructureToMemoryKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyMemoryToAccelerationStructureKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetDeviceAccelerationStructureCompatibilityKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceProperties2);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetRayTracingCaptureReplayShaderGroupHandlesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetRayTracingShaderGroupStackSizeKHR);
    /**********************************************************************************/
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetBufferDeviceAddressKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetDescriptorSetLayoutSupport);

    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceSurfaceSupportKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceSurfacePresentModesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceSurfaceCapabilitiesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceSurfaceFormatsKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateSwapchainKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetSwapchainImagesKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkAcquireNextImageKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkQueuePresentKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroySwapchainKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateInstance);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkEnumeratePhysicalDevices);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyInstance);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroySurfaceKHR);

    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetInstanceProcAddr);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetDeviceProcAddr);

    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceFeatures);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceFeatures2KHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceFormatProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceImageFormatProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceProperties2KHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceQueueFamilyProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceMemoryProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceMemoryProperties2KHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateDevice);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyDevice);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkEnumerateInstanceExtensionProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkEnumerateDeviceExtensionProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkEnumerateInstanceLayerProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkEnumerateDeviceLayerProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetDeviceQueue);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkQueueSubmit);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkQueueWaitIdle);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDeviceWaitIdle);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkAllocateMemory);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkFreeMemory);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkMapMemory);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkUnmapMemory);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkFlushMappedMemoryRanges);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkInvalidateMappedMemoryRanges);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetDeviceMemoryCommitment);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkBindBufferMemory);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkBindImageMemory);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetBufferMemoryRequirements);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetImageMemoryRequirements);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetBufferMemoryRequirements2KHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetImageMemoryRequirements2KHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetImageSparseMemoryRequirements);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPhysicalDeviceSparseImageFormatProperties);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkQueueBindSparse);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateFence);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyFence);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkResetFences);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetFenceStatus);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkWaitForFences);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateSemaphore);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroySemaphore);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateEvent);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyEvent);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetEventStatus);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkSetEvent);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkResetEvent);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateQueryPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyQueryPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetQueryPoolResults);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateBufferView);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyBufferView);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetImageSubresourceLayout);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateImageView);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyImageView);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateShaderModule);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyShaderModule);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreatePipelineCache);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyPipelineCache);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetPipelineCacheData);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkMergePipelineCaches);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateGraphicsPipelines);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateComputePipelines);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyPipeline);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreatePipelineLayout);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyPipelineLayout);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateSampler);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroySampler);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateDescriptorSetLayout);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyDescriptorSetLayout);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateDescriptorPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyDescriptorPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkResetDescriptorPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkAllocateDescriptorSets);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkFreeDescriptorSets);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkUpdateDescriptorSets);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateFramebuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyFramebuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateRenderPass);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyRenderPass);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkGetRenderAreaGranularity);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateCommandPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyCommandPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkResetCommandPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkTrimCommandPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkAllocateCommandBuffers);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkFreeCommandBuffers);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkBeginCommandBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkEndCommandBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkResetCommandBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBindPipeline);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetViewport);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetScissor);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetLineWidth);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetDepthBias);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetBlendConstants);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetDepthBounds);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetStencilCompareMask);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetStencilWriteMask);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetStencilReference);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBindDescriptorSets);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBindIndexBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBindVertexBuffers);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdDraw);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdDrawIndexed);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdDrawIndirect);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdDrawIndexedIndirect);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdDispatch);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdDispatchIndirect);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBlitImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyBufferToImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyImageToBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdUpdateBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdFillBuffer);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdClearColorImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdClearDepthStencilImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdClearAttachments);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdResolveImage);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdSetEvent);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdResetEvent);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdWaitEvents);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdPipelineBarrier);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBeginQuery);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdEndQuery);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdResetQueryPool);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdWriteTimestamp);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdCopyQueryPoolResults);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdPushConstants);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBeginRenderPass);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdNextSubpass);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdEndRenderPass);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdExecuteCommands);

    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdPushDescriptorSetKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdPushDescriptorSetWithTemplateKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateDescriptorUpdateTemplateKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkUpdateDescriptorSetWithTemplateKHR);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyDescriptorUpdateTemplateKHR);


    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCreateDebugReportCallbackEXT);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDebugReportMessageEXT);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkDestroyDebugReportCallbackEXT);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkSetDebugUtilsObjectNameEXT);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdBeginDebugUtilsLabelEXT);
    PVR_VULKAN_FUNCTION_POINTER_DECLARATION(vkCmdEndDebugUtilsLabelEXT);


    /* @brief Touch control thresholds from Android NDK samples */
    const int32_t DOUBLE_TAP_TIMEOUT = 300 * 1000000;
    const int32_t TAP_TIMEOUT        = 180 * 1000000;
    const int32_t DOUBLE_TAP_SLOP    = 100;
    const int32_t TAP_SLOP           = 8;


    /** @brief Density of the device screen (in DPI) */
    extern int32_t screenDensity;

    bool LoadVulkanLibrary();

    VkInstance GetLoadedInstance();
    VkDevice   GetLoadedDevice();

    void LoadVulkanInstanceFunctions(VkInstance instance);
    void LoadVulkanDeviceFunctions(VkDevice device);


    void FreeVulkanLibrary();
    void GetDeviceConfig();


    int  IsApiInited();
    void SetApiInited();
} // namespace vkfunc
